/// <reference path="./appearance.ts" />
/// <reference path="./bugs.ts" />
/// <reference path="./common.ts" />
/// <reference path="./errors.ts" />
/// <reference path="./events.ts" />
/// <reference path="./fish.ts" />
/// <reference path="./month.ts" />
/// <reference path="./today.ts" />
/// <reference path="./utils.ts" />
/// <reference path="./villagers.ts" />
declare namespace Nookipedia {}
